;; Generated by ChatGPT 15May23.  See https://sharegpt.com/c/oiZI35T 

;; Install packages
(unless (and (package-installed-p 'rjsx-mode)
             (package-installed-p 'company)
             (package-installed-p 'flycheck)
             (package-installed-p 'prettier-js))
  (package-refresh-contents)
  (package-install 'rjsx-mode)
  (package-install 'company)
  (package-install 'flycheck)
  (package-install 'prettier-js))

;; Enable rjsx-mode for .js and .jsx files
(add-to-list 'auto-mode-alist '("\\.jsx?$" . rjsx-mode))
(add-to-list 'auto-mode-alist '("components\\/.*\\.js\\'" . rjsx-mode))

;; Enable company mode globally
(add-hook 'after-init-hook 'global-company-mode)

;; Enable Company for autocompletion
(add-hook 'rjsx-mode-hook (lambda ()
                            (company-mode)))

;; Enable Flycheck globally
(add-hook 'after-init-hook #'global-flycheck-mode)

;; Use ESLint with Flycheck
(flycheck-add-mode 'javascript-eslint 'rjsx-mode)
(setq-default flycheck-disabled-checkers
              (append flycheck-disabled-checkers
                      '(javascript-jshint)))

(setq-default flycheck-temp-prefix ".flycheck")
(setq-default flycheck-javascript-eslint-executable "your-eslint-executable")

;; Enable prettier-js mode
(add-hook 'rjsx-mode-hook 'prettier-js-mode)

;; Run prettier on save
(defun run-prettier-js ()
  (interactive)
  (when (eq major-mode 'rjsx-mode)
    (prettier-js)))
(add-hook 'before-save-hook 'run-prettier-js)

;; [TODO] Dunno why this seems to be needed
(setq prettier-js-command "/opt/homebrew/bin/prettier")
